version: 1
phases:
  install:
    runtime=version:
      nodejs: 14
    commands:
      - echo "Installing dependencies"
      - npm install
      - npm install -g @angular/cli@12.2.5
  build:
    commands:
      - echo "Building Angular project" 
      - ng build --prod
  post_build:
    commands:
      - echo "Updating file in S3 bucket..."
      - aws s3 sync dist/github-s3-angular-app/ s3://mpowell-demo-2021 --delete
